### ISSUE TITLE
Add contributions guidelines and test cases

### ISSUE THREAD

**Issue by Seniru** [ehmicky/portable-files#1]
Hello!  I'm interested in contributing to this project. 

Could you add contribution guidelines to get a clearer idea of how other people can contribute to this project? 

Also I noticed that you have created a test folder but ire seems to be empty.  Can you create some test cases also?

**Comment by ehmicky** [comment]
Hi @Seniru, 

Thanks for your interest in this project but it is empty at the moment: no source code, no tests, no documentation. There's basically nothing to contribute to, it's just a placeholder name :)

**Comment by Seniru** [comment]
Oh! Can you notify me when this project start then?

**Comment by ehmicky** [comment]
Sure, will do! Thanks for your interest in this.

I am juggling with lots of projects at the moment, and I don't have a strong need for this `portable-files` library at the moment, so this might not happen anytime soon unfortunately :/
